version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "berlinglish"
s3_bucket = "aws-sam-cli-managed-deployment-2"
s3_prefix = "berlinglish"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"