name: Main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "::set-output name=NODE_VERSION::$(cat .nvmrc)"
        id: nvm
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - run: npm ci
      - run: npm run prettier:ci
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push'
    env:
      HOMEBREW_PATH: /home/linuxbrew/.linuxbrew/bin/brew
      SAM_PATH: /home/linuxbrew/.linuxbrew/opt/aws-sam-cli/bin/sam
    steps:
      - uses: actions/checkout@v2
      - name: Install Homebrew
        run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      - name: Tap AWS to Homebrew
        run: |
          $HOMEBREW_PATH tap aws/tap
      - name: Install AWS SAM CLI
        run: |
          $HOMEBREW_PATH install --force aws-sam-cli
      - name: SAM build
        run: $SAM_PATH build
      - name: SAM deploy
        run: $SAM_PATH deploy --parameter-overrides TwitterApiKey=$TWITTER_API_KEY TwitterApiSecretKey=$TWITTER_API_SECRET_KEY TwitterAccessToken=$TWITTER_ACCESS_TOKEN TwitterAccessTokenSecret=$TWITTER_ACCESS_TOKEN_SECRET
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
