name: Main

on:
  push:
    branches: [test]
  pull_request:
    branches: [master]

jobs:
  #   ci:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v2
  #       - uses: actions/setup-node@v1
  #         with:
  #           node-version: '12.x'
  #       - run: npm ci
  #       - run: npm run prettier:ci
  cd:
    runs-on: ubuntu-latest
    # needs: ci
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Install Homebrew
        run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      - name: Tap AWS to Homebrew
        run: |
          /home/linuxbrew/.linuxbrew/bin/brew tap aws/tap
      - name: Install AWS SAM CLI
        run: |
          /home/linuxbrew/.linuxbrew/bin/brew install aws-sam-cli
      - name: Finx AWS SAM CLI
        run: |
          /home/linuxbrew/.linuxbrew/bin/brew --prefix aws-sam-cli
      - name: Find AWS SAM CLI
        run: |
          /home/linuxbrew/.linuxbrew/bin/brew --cellar aws-sam-cli
      # FIXME: This is going to break
      - name: SAM build
        run: /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/bin/sam build
      - name: SAM deploy
        run: /home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/bin/sam deploy --parameter-overrides TwitterApiKey=$TWITTER_API_KEY TwitterApiSecretKey=$TWITTER_API_SECRET_KEY TwitterAccessToken=$TWITTER_ACCESS_TOKEN TwitterAccessTokenSecret=$TWITTER_ACCESS_TOKEN_SECRET
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
